# Generated by Django 6.0.1 on 2026-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
